[2023-03-12T10:58:17.786+0000] {processor.py:153} INFO - Started process (PID=7201) to work on /opt/airflow/dags/dag.py
[2023-03-12T10:58:17.788+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T10:58:17.791+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:17.791+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T10:58:17.830+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T10:58:18.086+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:18.086+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:dag
[2023-03-12T10:58:18.108+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:18.108+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:dag
[2023-03-12T10:58:18.118+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:18.118+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:dag
[2023-03-12T10:58:18.121+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:18.121+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T10:58:18.143+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:18.143+0000] {dag.py:2711} INFO - Creating ORM DAG for dag
[2023-03-12T10:58:18.166+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:18.166+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-11T00:00:00+00:00, run_after=2023-03-12T00:00:00+00:00
[2023-03-12T10:58:18.227+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.446 seconds
[2023-03-12T10:58:48.928+0000] {processor.py:153} INFO - Started process (PID=7271) to work on /opt/airflow/dags/dag.py
[2023-03-12T10:58:48.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T10:58:48.932+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:48.932+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T10:58:48.952+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T10:58:48.979+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:48.978+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T10:58:49.000+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:58:48.999+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T10:58:49.019+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.094 seconds
[2023-03-12T10:59:19.360+0000] {processor.py:153} INFO - Started process (PID=7350) to work on /opt/airflow/dags/dag.py
[2023-03-12T10:59:19.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T10:59:19.367+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:59:19.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T10:59:19.386+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T10:59:19.412+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:59:19.412+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T10:59:19.431+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:59:19.431+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T10:59:19.448+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.095 seconds
[2023-03-12T10:59:49.653+0000] {processor.py:153} INFO - Started process (PID=7416) to work on /opt/airflow/dags/dag.py
[2023-03-12T10:59:49.656+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T10:59:49.658+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:59:49.658+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T10:59:49.678+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T10:59:49.705+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:59:49.705+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T10:59:49.726+0000] {logging_mixin.py:137} INFO - [2023-03-12T10:59:49.726+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T10:59:49.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.093 seconds
[2023-03-12T11:00:19.952+0000] {processor.py:153} INFO - Started process (PID=7495) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:00:19.955+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:00:19.956+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:00:19.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:00:19.973+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:00:19.999+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:00:19.999+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:00:20.019+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:00:20.018+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:00:20.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.087 seconds
[2023-03-12T11:00:50.228+0000] {processor.py:153} INFO - Started process (PID=7561) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:00:50.232+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:00:50.235+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:00:50.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:00:50.255+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:00:50.281+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:00:50.281+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:00:50.303+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:00:50.303+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:00:50.320+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.099 seconds
[2023-03-12T11:01:20.482+0000] {processor.py:153} INFO - Started process (PID=7639) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:01:20.484+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:01:20.486+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:01:20.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:01:20.505+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:01:20.532+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:01:20.532+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:01:20.551+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:01:20.551+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:01:20.569+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.092 seconds
[2023-03-12T11:01:50.637+0000] {processor.py:153} INFO - Started process (PID=7713) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:01:50.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:01:50.641+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:01:50.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:01:50.665+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:01:50.694+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:01:50.694+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:01:50.715+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:01:50.715+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:01:50.733+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.101 seconds
[2023-03-12T11:02:20.946+0000] {processor.py:153} INFO - Started process (PID=7779) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:02:20.948+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:02:20.950+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:02:20.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:02:20.971+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:02:21.001+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:02:21.001+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:02:21.022+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:02:21.022+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:02:21.038+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.095 seconds
[2023-03-12T11:02:52.147+0000] {processor.py:153} INFO - Started process (PID=7856) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:02:52.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:02:52.152+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:02:52.152+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:02:52.172+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:02:52.204+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:02:52.204+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:02:52.230+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:02:52.230+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:02:52.251+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.108 seconds
[2023-03-12T11:03:22.375+0000] {processor.py:153} INFO - Started process (PID=7922) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:03:22.378+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:03:22.380+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:03:22.379+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:03:22.399+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:03:22.428+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:03:22.428+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:03:22.451+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:03:22.451+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:03:22.464+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.093 seconds
[2023-03-12T11:03:52.917+0000] {processor.py:153} INFO - Started process (PID=7985) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:03:52.918+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:03:52.921+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:03:52.921+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:03:52.941+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:03:52.966+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:03:52.966+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:03:52.987+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:03:52.987+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:03:53.002+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.088 seconds
[2023-03-12T11:04:23.166+0000] {processor.py:153} INFO - Started process (PID=8050) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:04:23.178+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:04:23.184+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:04:23.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:04:23.223+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dag']) retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:04:23.260+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:04:23.260+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-12T11:04:23.301+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:04:23.301+0000] {dag.py:3441} INFO - Setting next_dagrun for dag to 2023-03-12T00:00:00+00:00, run_after=2023-03-13T00:00:00+00:00
[2023-03-12T11:04:23.320+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.158 seconds
[2023-03-12T11:04:39.643+0000] {processor.py:153} INFO - Started process (PID=8102) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:04:39.642+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:04:39.646+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:04:39.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:04:39.669+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:04:39.665+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 9
    from airflow-docker.scripts.2_2_Introduction_to_ETL import extract_currency
                ^
SyntaxError: invalid syntax
[2023-03-12T11:04:39.670+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:04:39.709+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.079 seconds
[2023-03-12T11:04:49.737+0000] {processor.py:153} INFO - Started process (PID=8116) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:04:49.739+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:04:49.742+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:04:49.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:04:49.754+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:04:49.753+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 9
    from scripts.2_2_Introduction_to_ETL import extract_currency
                    ^
SyntaxError: invalid token
[2023-03-12T11:04:49.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:04:49.778+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2023-03-12T11:05:19.999+0000] {processor.py:153} INFO - Started process (PID=8182) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:05:20.003+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:05:20.006+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:05:20.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:05:20.023+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:05:20.020+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 9
    from scripts.2_2_Introduction_to_ETL import extract_currency
                    ^
SyntaxError: invalid token
[2023-03-12T11:05:20.025+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:05:20.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.061 seconds
[2023-03-12T11:05:23.446+0000] {processor.py:153} INFO - Started process (PID=8200) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:05:23.449+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:05:23.456+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:05:23.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:05:25.434+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:05:25.430+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 9, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:05:25.436+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:05:25.455+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 2.014 seconds
[2023-03-12T11:05:32.916+0000] {processor.py:153} INFO - Started process (PID=8238) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:05:32.918+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:05:32.919+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:05:32.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:05:32.928+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:05:32.928+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:05:32.931+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:05:32.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2023-03-12T11:05:57.321+0000] {processor.py:153} INFO - Started process (PID=8304) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:05:57.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:05:57.330+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:05:57.329+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:05:57.342+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:05:57.342+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:05:57.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:05:57.372+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.055 seconds
[2023-03-12T11:06:19.703+0000] {processor.py:153} INFO - Started process (PID=8331) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:06:19.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:06:19.716+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:06:19.715+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:06:19.740+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:06:19.737+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:06:19.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:06:19.818+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.128 seconds
[2023-03-12T11:06:50.866+0000] {processor.py:153} INFO - Started process (PID=8410) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:06:50.870+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:06:50.872+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:06:50.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:06:50.879+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:06:50.879+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:06:50.881+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:06:50.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
[2023-03-12T11:07:21.241+0000] {processor.py:153} INFO - Started process (PID=8485) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:07:21.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:07:21.245+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:07:21.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:07:21.250+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:07:21.250+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:07:21.252+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:07:21.275+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
[2023-03-12T11:07:51.478+0000] {processor.py:153} INFO - Started process (PID=8554) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:07:51.481+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:07:51.483+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:07:51.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:07:51.490+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:07:51.490+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:07:51.493+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:07:51.524+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.053 seconds
[2023-03-12T11:08:12.744+0000] {processor.py:153} INFO - Started process (PID=8619) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:08:12.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:08:12.760+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:08:12.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:08:12.813+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:08:12.806+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:08:12.817+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:08:12.863+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.133 seconds
[2023-03-12T11:08:43.063+0000] {processor.py:153} INFO - Started process (PID=8685) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:08:43.067+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:08:43.069+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:08:43.069+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:08:43.085+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:08:43.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:08:43.092+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:08:43.130+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.078 seconds
[2023-03-12T11:09:13.458+0000] {processor.py:153} INFO - Started process (PID=8764) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:09:13.462+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:09:13.464+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:09:13.464+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:09:13.479+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:09:13.475+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:09:13.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:09:13.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2023-03-12T11:09:14.508+0000] {processor.py:153} INFO - Started process (PID=8765) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:09:14.511+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:09:14.513+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:09:14.513+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:09:14.529+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:09:14.527+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:09:14.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:09:14.580+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.076 seconds
[2023-03-12T11:09:44.713+0000] {processor.py:153} INFO - Started process (PID=8844) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:09:44.717+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:09:44.719+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:09:44.718+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:09:44.738+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:09:44.735+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:09:44.740+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:09:44.783+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.079 seconds
[2023-03-12T11:10:15.236+0000] {processor.py:153} INFO - Started process (PID=8910) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:10:15.243+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:10:15.245+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:10:15.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:10:15.257+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:10:15.255+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:10:15.259+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:10:15.286+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.055 seconds
[2023-03-12T11:10:45.977+0000] {processor.py:153} INFO - Started process (PID=8989) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:10:45.981+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:10:45.984+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:10:45.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:10:45.999+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:10:45.997+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:10:46.002+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:10:46.022+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2023-03-12T11:13:18.979+0000] {processor.py:153} INFO - Started process (PID=9354) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:13:18.983+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:13:18.985+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:13:18.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:13:19.002+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:13:18.999+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:13:19.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:13:19.034+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2023-03-12T11:13:50.049+0000] {processor.py:153} INFO - Started process (PID=9421) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:13:50.052+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:13:50.054+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:13:50.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:13:50.064+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:13:50.062+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:13:50.065+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:13:50.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2023-03-12T11:13:58.164+0000] {processor.py:153} INFO - Started process (PID=9434) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:13:58.167+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:13:58.169+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:13:58.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:13:58.186+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:13:58.184+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:13:58.189+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:13:58.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.074 seconds
[2023-03-12T11:14:28.447+0000] {processor.py:153} INFO - Started process (PID=9513) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:14:28.449+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:14:28.451+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:14:28.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:14:28.461+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:14:28.460+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:14:28.465+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:14:28.507+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2023-03-12T11:14:34.494+0000] {processor.py:153} INFO - Started process (PID=9538) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:14:34.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:14:34.501+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:14:34.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:14:34.543+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:14:34.541+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 37
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:14:34.547+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:14:34.573+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.085 seconds
[2023-03-12T11:14:54.885+0000] {processor.py:153} INFO - Started process (PID=9580) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:14:54.889+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:14:54.891+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:14:54.891+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:14:54.909+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:14:54.907+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:14:54.912+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:14:54.941+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2023-03-12T11:15:25.502+0000] {processor.py:153} INFO - Started process (PID=9645) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:15:25.505+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:15:25.508+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:15:25.508+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:15:25.520+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:15:25.518+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:15:25.522+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:15:25.553+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2023-03-12T11:15:55.811+0000] {processor.py:153} INFO - Started process (PID=9725) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:15:55.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:15:55.819+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:15:55.818+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:15:55.840+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:15:55.837+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:15:55.843+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:15:55.887+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.084 seconds
[2023-03-12T11:16:26.433+0000] {processor.py:153} INFO - Started process (PID=9804) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:16:26.435+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:16:26.437+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:16:26.437+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:16:26.447+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:16:26.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:16:26.450+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:16:26.468+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
[2023-03-12T11:16:51.650+0000] {processor.py:153} INFO - Started process (PID=9869) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:16:51.653+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:16:51.656+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:16:51.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:16:51.680+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:16:51.678+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:16:51.682+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:16:51.723+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.080 seconds
[2023-03-12T11:17:22.089+0000] {processor.py:153} INFO - Started process (PID=9934) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:17:22.092+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:17:22.094+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:17:22.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:17:22.106+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:17:22.104+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:17:22.107+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:17:22.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2023-03-12T11:17:53.159+0000] {processor.py:153} INFO - Started process (PID=10013) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:17:53.163+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:17:53.166+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:17:53.166+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:17:53.180+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:17:53.178+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:17:53.184+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:17:53.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2023-03-12T11:18:23.481+0000] {processor.py:153} INFO - Started process (PID=10086) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:18:23.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:18:23.490+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:18:23.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:18:23.502+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:18:23.500+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:18:23.505+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:18:23.536+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.061 seconds
[2023-03-12T11:18:53.903+0000] {processor.py:153} INFO - Started process (PID=10157) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:18:53.906+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:18:53.909+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:18:53.909+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:18:53.919+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:18:53.918+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:18:53.920+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:18:53.943+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2023-03-12T11:19:23.985+0000] {processor.py:153} INFO - Started process (PID=10237) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:19:23.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:19:23.990+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:19:23.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:19:24.002+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:19:24.001+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:19:24.007+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:19:24.032+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2023-03-12T11:19:55.112+0000] {processor.py:153} INFO - Started process (PID=10303) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:19:55.116+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:19:55.121+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:19:55.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:19:55.138+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:19:55.135+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:19:55.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:19:55.173+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.068 seconds
[2023-03-12T11:20:22.215+0000] {processor.py:153} INFO - Started process (PID=10381) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:20:22.217+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:20:22.220+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:20:22.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:20:22.245+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:20:22.239+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 29
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:20:22.247+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:20:22.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.078 seconds
[2023-03-12T11:20:47.512+0000] {processor.py:153} INFO - Started process (PID=10448) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:20:47.516+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:20:47.518+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:20:47.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:20:47.540+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:20:47.537+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:20:47.543+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:20:47.572+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2023-03-12T11:21:18.110+0000] {processor.py:153} INFO - Started process (PID=10514) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:21:18.114+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:21:18.116+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:21:18.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:21:18.130+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:21:18.128+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:21:18.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:21:18.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2023-03-12T11:21:48.257+0000] {processor.py:153} INFO - Started process (PID=10593) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:21:48.261+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:21:48.264+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:21:48.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:21:48.280+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:21:48.278+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:21:48.282+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:21:48.316+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.068 seconds
[2023-03-12T11:22:18.659+0000] {processor.py:153} INFO - Started process (PID=10659) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:22:18.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:22:18.668+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:22:18.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:22:18.684+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:22:18.683+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11
    'retries': 5,
             ^
SyntaxError: invalid syntax
[2023-03-12T11:22:18.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:22:18.713+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2023-03-12T11:22:32.847+0000] {processor.py:153} INFO - Started process (PID=10686) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:22:32.850+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:22:32.853+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:22:32.853+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:22:32.907+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:22:32.896+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:22:32.909+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:22:32.941+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.102 seconds
[2023-03-12T11:23:03.297+0000] {processor.py:153} INFO - Started process (PID=10751) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:23:03.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:23:03.302+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:23:03.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:23:03.330+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:23:03.323+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:23:03.332+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:23:03.363+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.069 seconds
[2023-03-12T11:23:33.451+0000] {processor.py:153} INFO - Started process (PID=10831) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:23:33.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:23:33.456+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:23:33.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:23:33.483+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:23:33.478+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:23:33.487+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:23:33.520+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.075 seconds
[2023-03-12T11:24:03.825+0000] {processor.py:153} INFO - Started process (PID=10897) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:24:03.828+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:24:03.830+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:24:03.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:24:03.868+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:24:03.858+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:24:03.870+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:24:03.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.084 seconds
[2023-03-12T11:24:34.421+0000] {processor.py:153} INFO - Started process (PID=10976) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:24:34.425+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:24:34.428+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:24:34.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:24:34.478+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:24:34.466+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:24:34.482+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:24:34.509+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.095 seconds
[2023-03-12T11:25:05.358+0000] {processor.py:153} INFO - Started process (PID=11054) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:25:05.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:25:05.365+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:25:05.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:25:05.397+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:25:05.390+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:25:05.400+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:25:05.443+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.094 seconds
[2023-03-12T11:25:35.553+0000] {processor.py:153} INFO - Started process (PID=11121) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:25:35.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:25:35.558+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:25:35.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:25:35.576+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:25:35.572+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:25:35.582+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:25:35.600+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2023-03-12T11:26:05.827+0000] {processor.py:153} INFO - Started process (PID=11200) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:26:05.829+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:26:05.832+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:26:05.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:26:05.853+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:26:05.848+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:26:05.856+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:26:05.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2023-03-12T11:26:36.138+0000] {processor.py:153} INFO - Started process (PID=11267) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:26:36.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:26:36.143+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:26:36.143+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:26:36.181+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:26:36.174+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:26:36.183+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:26:36.211+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.077 seconds
[2023-03-12T11:27:31.987+0000] {processor.py:153} INFO - Started process (PID=11281) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:27:31.990+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:27:31.993+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:27:31.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:27:32.016+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:27:32.011+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:27:32.018+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:27:32.037+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2023-03-12T11:28:02.882+0000] {processor.py:153} INFO - Started process (PID=11347) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:28:02.885+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:28:02.890+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:28:02.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:28:02.926+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:28:02.910+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:28:02.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:28:02.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.078 seconds
[2023-03-12T11:29:33.454+0000] {processor.py:153} INFO - Started process (PID=11426) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:29:33.457+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:29:33.459+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:29:33.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:29:33.491+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:29:33.485+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:29:33.493+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:29:33.519+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.071 seconds
[2023-03-12T11:30:03.598+0000] {processor.py:153} INFO - Started process (PID=11499) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:30:03.602+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:30:03.605+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:30:03.604+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:30:03.645+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:30:03.632+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:30:03.647+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:30:03.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.082 seconds
[2023-03-12T11:30:33.932+0000] {processor.py:153} INFO - Started process (PID=11571) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:30:33.937+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:30:33.939+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:30:33.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:30:33.958+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:30:33.954+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:30:33.961+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:30:33.980+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.053 seconds
[2023-03-12T11:32:13.990+0000] {processor.py:153} INFO - Started process (PID=11650) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:32:13.992+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:32:13.994+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:32:13.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:32:14.025+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:32:14.018+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:32:14.027+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:32:14.084+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.100 seconds
[2023-03-12T11:32:44.640+0000] {processor.py:153} INFO - Started process (PID=11716) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:32:44.644+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:32:44.645+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:32:44.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:32:44.681+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:32:44.673+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:32:44.683+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:32:44.710+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.076 seconds
[2023-03-12T11:33:15.033+0000] {processor.py:153} INFO - Started process (PID=11794) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:33:15.040+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:33:15.043+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:33:15.043+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:33:15.077+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:33:15.067+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:33:15.078+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:33:15.128+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.101 seconds
[2023-03-12T11:33:45.483+0000] {processor.py:153} INFO - Started process (PID=11860) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:33:45.487+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:33:45.490+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:33:45.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:33:45.534+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:33:45.524+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:33:45.535+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:33:45.568+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.093 seconds
[2023-03-12T11:34:13.271+0000] {processor.py:153} INFO - Started process (PID=11938) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:34:13.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:34:13.280+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:34:13.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:34:13.364+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:34:13.352+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    import scripts.Introduction_to_ETL_2_2
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:34:13.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:34:13.409+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.147 seconds
[2023-03-12T11:34:43.779+0000] {processor.py:153} INFO - Started process (PID=12004) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:34:43.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:34:43.785+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:34:43.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:34:43.827+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:34:43.817+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    import scripts.Introduction_to_ETL_2_2
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:34:43.829+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:34:43.866+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.094 seconds
[2023-03-12T11:34:46.903+0000] {processor.py:153} INFO - Started process (PID=12014) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:34:46.906+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:34:46.908+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:34:46.908+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:34:46.979+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:34:46.965+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:34:46.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:34:47.012+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.127 seconds
[2023-03-12T11:35:17.206+0000] {processor.py:153} INFO - Started process (PID=12084) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:35:17.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:35:17.212+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:35:17.212+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:35:17.260+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:35:17.247+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:35:17.263+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:35:17.296+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.099 seconds
[2023-03-12T11:35:47.433+0000] {processor.py:153} INFO - Started process (PID=12162) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:35:47.436+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:35:47.439+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:35:47.438+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:35:47.476+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:35:47.469+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
ModuleNotFoundError: No module named 'scripts'
[2023-03-12T11:35:47.478+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:35:47.504+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.077 seconds
[2023-03-12T11:36:11.631+0000] {processor.py:153} INFO - Started process (PID=12228) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:36:11.634+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:36:11.636+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:36:11.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:36:11.654+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:36:11.651+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6
    from ~/airflow-docker/scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
         ^
SyntaxError: invalid syntax
[2023-03-12T11:36:11.656+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:36:11.688+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.063 seconds
[2023-03-12T11:36:42.333+0000] {processor.py:153} INFO - Started process (PID=12294) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:36:42.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:36:42.338+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:36:42.338+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:36:42.348+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:36:42.346+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6
    from ~/airflow-docker/scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
         ^
SyntaxError: invalid syntax
[2023-03-12T11:36:42.351+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:36:42.369+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
[2023-03-12T11:37:13.352+0000] {processor.py:153} INFO - Started process (PID=12373) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:37:13.354+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:37:13.357+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:37:13.357+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:37:13.368+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:37:13.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6
    from ~/airflow-docker/scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
         ^
SyntaxError: invalid syntax
[2023-03-12T11:37:13.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:37:13.389+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2023-03-12T11:37:43.513+0000] {processor.py:153} INFO - Started process (PID=12451) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:37:43.516+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:37:43.517+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:37:43.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:37:43.527+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:37:43.526+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6
    from ~/airflow-docker/scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
         ^
SyntaxError: invalid syntax
[2023-03-12T11:37:43.528+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:37:43.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.036 seconds
[2023-03-12T11:38:13.838+0000] {processor.py:153} INFO - Started process (PID=12518) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:38:13.841+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:38:13.843+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:38:13.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:38:13.856+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:38:13.854+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6
    from ~/airflow-docker/scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
         ^
SyntaxError: invalid syntax
[2023-03-12T11:38:13.859+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:38:13.883+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2023-03-12T11:38:44.257+0000] {processor.py:153} INFO - Started process (PID=12597) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:38:44.261+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:38:44.265+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:38:44.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:38:44.280+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:38:44.277+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6
    from ~/airflow-docker/scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
         ^
SyntaxError: invalid syntax
[2023-03-12T11:38:44.282+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:38:44.313+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.065 seconds
[2023-03-12T11:39:15.136+0000] {processor.py:153} INFO - Started process (PID=12663) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:39:15.139+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:39:15.142+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:39:15.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:39:15.158+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:39:15.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6
    from ~/airflow-docker/scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
         ^
SyntaxError: invalid syntax
[2023-03-12T11:39:15.159+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:39:15.207+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.083 seconds
[2023-03-12T11:39:17.239+0000] {processor.py:153} INFO - Started process (PID=12677) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:39:17.241+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:39:17.245+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:39:17.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:39:17.260+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:39:17.259+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 9
    from ~/airflow-docker/scripts.Introduction_to_ETL_2_2 import extract_currency, insert_to_db, extract_data
         ^
SyntaxError: invalid syntax
[2023-03-12T11:39:17.265+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:39:17.296+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.071 seconds
[2023-03-12T11:39:27.064+0000] {processor.py:153} INFO - Started process (PID=12717) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:39:27.069+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:39:27.073+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:39:27.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:39:27.112+0000] {logging_mixin.py:137} INFO - /opt/airflow
[2023-03-12T11:39:27.115+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:39:27.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.092 seconds
[2023-03-12T11:39:57.688+0000] {processor.py:153} INFO - Started process (PID=12797) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:39:57.690+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:39:57.692+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:39:57.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:39:57.706+0000] {logging_mixin.py:137} INFO - /opt/airflow
[2023-03-12T11:39:57.708+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:39:57.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2023-03-12T11:40:07.862+0000] {processor.py:153} INFO - Started process (PID=12811) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:40:07.868+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:40:07.871+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:40:07.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:40:07.899+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:40:07.897+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7
    from Users/anatoliyzhukov/airflow-docker/scripts/scripts.Introduction_to_ETL_2_2 import extract_currency, \
              ^
SyntaxError: invalid syntax
[2023-03-12T11:40:07.901+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:40:07.948+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.093 seconds
[2023-03-12T11:40:34.080+0000] {processor.py:153} INFO - Started process (PID=12877) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:40:34.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:40:34.086+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:40:34.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:40:34.107+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:40:34.104+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7
    from users/anatoliyzhukov/airflow-docker/scripts/scripts.Introduction_to_ETL_2_2 import extract_currency, \
              ^
SyntaxError: invalid syntax
[2023-03-12T11:40:34.109+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:40:34.140+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.071 seconds
[2023-03-12T11:41:04.717+0000] {processor.py:153} INFO - Started process (PID=12951) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:41:04.720+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:41:04.722+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:41:04.722+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:41:04.738+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:41:04.736+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7
    from users/anatoliyzhukov/airflow-docker/scripts/scripts.Introduction_to_ETL_2_2 import extract_currency, \
              ^
SyntaxError: invalid syntax
[2023-03-12T11:41:04.741+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:41:04.775+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.065 seconds
[2023-03-12T11:41:07.753+0000] {processor.py:153} INFO - Started process (PID=12956) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:41:07.758+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:41:07.760+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:41:07.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:41:07.785+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:41:07.782+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7
    from airflow-docker/scripts/scripts.Introduction_to_ETL_2_2 import extract_currency, \
                ^
SyntaxError: invalid syntax
[2023-03-12T11:41:07.789+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:41:07.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.104 seconds
[2023-03-12T11:41:38.535+0000] {processor.py:153} INFO - Started process (PID=13022) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:41:38.537+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:41:38.539+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:41:38.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:41:38.553+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:41:38.550+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7
    from airflow-docker/scripts/scripts.Introduction_to_ETL_2_2 import extract_currency, \
                ^
SyntaxError: invalid syntax
[2023-03-12T11:41:38.554+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:41:38.582+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2023-03-12T11:42:09.217+0000] {processor.py:153} INFO - Started process (PID=13102) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:42:09.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:42:09.223+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:42:09.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:42:09.238+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:42:09.236+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7
    from airflow-docker/scripts/scripts.Introduction_to_ETL_2_2 import extract_currency, \
                ^
SyntaxError: invalid syntax
[2023-03-12T11:42:09.239+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:42:09.272+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2023-03-12T11:42:13.312+0000] {processor.py:153} INFO - Started process (PID=13103) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:42:13.315+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:42:13.318+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:42:13.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:42:13.327+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:42:13.326+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:42:13.328+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:42:13.348+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2023-03-12T11:42:19.407+0000] {processor.py:153} INFO - Started process (PID=13118) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:42:19.414+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:42:19.418+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:42:19.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:42:19.427+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:42:19.426+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:42:19.428+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:42:19.456+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2023-03-12T11:42:50.106+0000] {processor.py:153} INFO - Started process (PID=13185) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:42:50.109+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:42:50.110+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:42:50.110+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:42:50.118+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:42:50.118+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:42:50.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:42:50.143+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2023-03-12T11:43:00.195+0000] {processor.py:153} INFO - Started process (PID=13238) to work on /opt/airflow/dags/dag.py
[2023-03-12T11:43:00.198+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-03-12T11:43:00.200+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:43:00.200+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-03-12T11:43:00.209+0000] {logging_mixin.py:137} INFO - [2023-03-12T11:43:00.209+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag.py assumed to contain no DAGs. Skipping.
[2023-03-12T11:43:00.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-03-12T11:43:00.230+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
